scrape_configs:
  - job_name: 'service-alpha'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-alpha:8080' ]
  - job_name: 'service-bravo'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-bravo:8080' ]
  - job_name: 'service-charlie' # won't work - this service doesn't have a web interface
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-charlie:8080' ]
  - job_name: 'service-discovery'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-discovery:8761' ]
  - job_name: 'service-gateway'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-gateway:8080' ]
